### ISSUE TITLE
Rebar name overload

### ISSUE THREAD

**Issue by wrq** [BurntSushi/rebar#5]
Feel free to close this if it doesn’t bother you, just thought I’d chirp your direction and let you know. 

Rebar is also the name of a rather venerable and respected tool in the Erlang ecosystem, it does builds, config and such things.

https://github.com/erlang/rebar3

**Comment by BurntSushi** [comment]
Name clashes are inevitable. While these tools share the same name, they don't look confuseable to me. So I don't see a compelling reason to change the name.

**Comment by BurntSushi** [comment]
Thank you for the heads up though!
