### ISSUE TITLE
is it possible to use re2 as a system package instead of compiling?

### ISSUE THREAD

**Issue by jonstewart** [BurntSushi/rebar#6]
I'm getting a compile error for re2 when running `rebar build` on macOS Monterey (with debug logging it complains that abseil isn't installed; when I installed abseil with macports, it then complains about C++ version support mismatch, which I haven't bothered figuring out yet because it's Friday night).

However, I have libre2 installed as a package already (v2.11). What's involved with getting rebar just to use that rather than building itself? (If the answer is a lot, that's understandable and then I'm probably better off figuring out the C++ version error.)

**Comment by jonstewart** [comment]
It's a lot of error output, but to avoid being [DenverCoder9](https://xkcd.com/979/), here is the debug output I get trying to build re2 with rebar:
[re2_build_output.txt](https://github.com/BurntSushi/rebar/files/12326298/re2_build_output.txt)

**Comment by jonstewart** [comment]
Related to the re2 build error, fixing it is straightforward. Leaving `cc` at version 1.0.73, adding
```
builder.flag("-std=c++15");
```
at https://github.com/BurntSushi/rebar/blob/master/engines/re2/build.rs#L25 will build re2 on macos (at least on Arm cacs, I will check on my old Intel mac later).

The current version of `cc`, 1.0.83, adds the `std()` method to `Build`, so it could also be `builder.std("c++14");` with an upgrade to `cc` in engines/re2/Cargo.toml.

Do you have a preference? I'm wondering whether you had a reason for pegging cc to 1.0.73. Either way, I don't mind working up a PR.

**Comment by BurntSushi** [comment]
Hmmm, I'm still stuck on the build not being able to find abseil. In my case, I installed abseil via Homebrew:

```
$ brew reinstall abseil
==> Fetching abseil
==> Downloading https://ghcr.io/v2/homebrew/core/abseil/manifests/20230125.3-1
Already downloaded: /Users/andrew/Library/Caches/Homebrew/downloads/0b82c12660c543853c3389b148eefd53dc181b8babf0c56d0d879db291c01282--abseil-20230125.3-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/abseil/blobs/sha256:c789ff211d0d81fba211ffa4abc0a0e5ce430698ae0e590057cbeeb73d620d15
Already downloaded: /Users/andrew/Library/Caches/Homebrew/downloads/364b2988a033ba6fe15cbe357a269a71717f266de0723a1e660d459bf5494e2b--abseil--20230125.3.arm64_ventura.bottle.1.tar.gz
==> Reinstalling abseil
==> Pouring abseil--20230125.3.arm64_ventura.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/abseil/20230125.3: 723 files, 10.6MB
==> Running `brew cleanup abseil`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ cargo b
   Compiling main v0.0.0 (/Users/andrew/rust/rebar/engines/re2)
The following warnings were emitted during compilation:

warning: upstream/re2/compile.cc:15:10: fatal error: 'absl/base/macros.h' file not found
warning: #include "absl/base/macros.h"
warning:          ^~~~~~~~~~~~~~~~~~~~
warning: In file included from upstream/re2/set.cc:5:
warning: upstream/re2/set.h:13:10: fatal error: 'absl/strings/string_view.h' file not found
warning: #include "absl/strings/string_view.h"
warning:          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[... snip ...]
```

I'm kind of out of my depth on macOS, so I'm not quite sure where to go from here. Anyway, I've pushed a commit to master with your changes. (`cc` wasn't pegged to 1.0.73. The 1.0.73 in the `Cargo.toml` just means, "this is the minimal version to use and don't automatically upgrade to semver incompatible versions when `cargo update` is run." I've changed the minimal version to 1.0.83.)

**Comment by BurntSushi** [comment]
And sorry about the late reply! I meant to respond sooner but this dropped too far in my inbox and I lost track of it. :(

**Comment by jonstewart** [comment]
I don't know homebrew very well. Presumably /opt/homebrew/Cellar/abseil/20230125.3/base/macros.h exists? (Or maybe /opt/homebrew/Cellar/abseil/20230125.3/abseil/base/macros.h?) And presumably there's some kind of symlink of the abseil directory into something like /opt/homebrew/include?

The basic error is that the compiler can't find these headers. There are two ways to let them know where they are, environment variables or the RE2/Abseil build system configuring itself to find them. With environment variables, you could set `CPATH` with the correct Homebrew include directory. http://gcc.gnu.org/onlinedocs/cpp/Environment-Variables.html

**Comment by BurntSushi** [comment]
Nice! `CPATH` let me move forward. Now I get new errors:

```
$ CPATH=/opt/homebrew/include cargo b
   Compiling main v0.0.0 (/Users/andrew/rust/rebar/engines/re2)
The following warnings were emitted during compilation:

warning: In file included from upstream/re2/onepass.cc:60:
warning: In file included from /opt/homebrew/include/absl/container/fixed_array.h:50:
warning: In file included from /opt/homebrew/include/absl/container/internal/compressed_tuple.h:40:
warning: /opt/homebrew/include/absl/utility/utility.h:164:12: error: no member named 'in_place_t' in namespace 'std'
warning: using std::in_place_t;
warning:       ~~~~~^
warning: /opt/homebrew/include/absl/utility/utility.h:165:12: error: no member named 'in_place' in namespace 'std'
warning: using std::in_place;
warning:       ~~~~~^
warning: /opt/homebrew/include/absl/utility/utility.h:181:12: error: no member named 'in_place_type' in namespace 'std'
warning: using std::in_place_type;
warning:       ~~~~~^
warning: /opt/homebrew/include/absl/utility/utility.h:182:12: error: no member named 'in_place_type_t' in namespace 'std'
warning: using std::in_place_type_t;
```

(And more like it.)

Don't feel obligated to help me debug here. :-)

**Comment by jonstewart** [comment]
std::in_place_type_t was added to C++ in C++17. Maybe try passing "c++17"
in the call to std() to see whether that resolves?

C++17 is pretty well supported these days but it does seem like a bit
aggressive of a requirement on behalf of Abseil.

**Comment by BurntSushi** [comment]
Yup, that did the trick. Thank you! I've pushed an update to the `build.rs` file.

**Comment by jonstewart** [comment]
Apparently Abseil itself only requires C++14, but, for unknown reasons, the Homebrew package for it requires C++17. 🤷‍♂️
