### ISSUE TITLE
Documentation of .NET engine incorrect?

### ISSUE THREAD

**Issue by Aloso** [BurntSushi/rebar#8]
The documentation says:

> .NET's regex engine has pretty good Unicode support. It does Unicode case folding for case insensitive matching, `\w`/`\s`/`\d` are all Unicode-aware. `\b` is also Unicode-aware. And things like `.` match entire codepoints.

I could not reproduce this. In my tests, `\w`, `\s`, `\d` and `.` always matched a single UTF-16 code unit. For example, the string `-💩-` can be matched with the regex `-..-`, but not with `-.-`, which works in other Regex engines that support Unicode. Furthermore, the regex `\p{L}` did not match the string `𠀋`; in my tests, it only works for code points in the BMP (below U+10000).

If I am correct (and [this issue](https://github.com/dotnet/runtime/issues/16922) seems to confirm my suspicion), the docs should be adjusted to mention this, because it means that .NET does less work than other engines, and may occasionally produce wrong results.

I used
- Mono C# compiler version 6.12.0.0
- Mono JIT compiler version 6.12.0 (makepkg/d9a6e8710b3 Thu Aug 31 10:53:20 UTC 2023)

**Comment by BurntSushi** [comment]
Good catch. I discovered exactly that when writing Unicode tests for all engines. See here: https://github.com/BurntSushi/rebar/blob/7c2fcbf08843b51845a6885bf124f23f7667aa51/benchmarks/definitions/test/unicode/letter.toml#L85-L131

I've updated the docs to reflect actual behavior.
